version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - '8123:8123'  # HTTP interface
      - '9000:9000'  # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - clickhouse_net
      - app_net
      - prometheus_net
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 500MB


volumes:
  clickhouse_data:

networks:
  clickhouse_net:
    name: clickhouse_net
  app_net:
    external: true
    name: app_net
    driver: bridge
  prometheus_net:
    external: True
    name: prometheus_net

